"""
应用常量定义
"""

# 应用信息
APP_NAME = "FLUKE 8846A Control"
APP_VERSION = "0.1.0"
APP_DESCRIPTION = "Control application for FLUKE 8846A Digital Multimeter"

# 通信接口类型
INTERFACE_GPIB = "GPIB"
INTERFACE_USB = "USB"
INTERFACE_SERIAL = "SERIAL"
INTERFACE_MOCK = "MOCK"
INTERFACES = [INTERFACE_GPIB, INTERFACE_USB, INTERFACE_SERIAL, INTERFACE_MOCK]

# 测量功能
MEASUREMENT_DCV = "DCV"      # 直流电压
MEASUREMENT_ACV = "ACV"      # 交流电压
MEASUREMENT_DCI = "DCI"      # 直流电流
MEASUREMENT_ACI = "ACI"      # 交流电流
MEASUREMENT_OHM = "OHM"      # 电阻
MEASUREMENT_FREQ = "FREQ"    # 频率
MEASUREMENTS = [
    MEASUREMENT_DCV,
    MEASUREMENT_ACV,
    MEASUREMENT_DCI,
    MEASUREMENT_ACI,
    MEASUREMENT_OHM,
    MEASUREMENT_FREQ,
]

# 测量范围
RANGE_AUTO = "AUTO"
RANGE_100mV = "100mV"
RANGE_1V = "1V"
RANGE_10V = "10V"
RANGE_100V = "100V"
RANGE_1000V = "1000V"
VOLTAGE_RANGES = [RANGE_AUTO, RANGE_100mV, RANGE_1V, RANGE_10V, RANGE_100V, RANGE_1000V]

# 分辨率
RESOLUTION_3_5 = "3.5"      # 3.5位
RESOLUTION_4_5 = "4.5"      # 4.5位
RESOLUTION_5_5 = "5.5"      # 5.5位
RESOLUTION_6_5 = "6.5"      # 6.5位
RESOLUTIONS = [RESOLUTION_3_5, RESOLUTION_4_5, RESOLUTION_5_5, RESOLUTION_6_5]

# 默认值
DEFAULT_TIMEOUT = 5000  # 毫秒
DEFAULT_INTERVAL = 1.0  # 秒
DEFAULT_SAMPLE_COUNT = 10

# 错误码
ERROR_SUCCESS = 0
ERROR_CONNECTION_FAILED = 1
ERROR_COMMUNICATION_FAILED = 2
ERROR_INVALID_PARAMETER = 3
ERROR_DEVICE_NOT_FOUND = 4
ERROR_MEASUREMENT_FAILED = 5

# 文件扩展名
EXT_CSV = ".csv"
EXT_JSON = ".json"
EXT_EXCEL = ".xlsx"

# 主题
THEME_LIGHT = "light"
THEME_DARK = "dark"
THEMES = [THEME_LIGHT, THEME_DARK]

# 语言
LANGUAGE_ZH_CN = "zh_CN"
LANGUAGE_EN_US = "en_US"
LANGUAGES = [LANGUAGE_ZH_CN, LANGUAGE_EN_US]